"use client"

import { useEffect, useState, useRef, useMemo } from "react"
import axios from "axios"
import { useParams } from "react-router-dom"
import { FileText, AlertCircle } from "lucide-react"

const LiveMeeting = () => {
  const { id } = useParams()
  const [meeting, setMeeting] = useState<any>(null)
  const [loading, setLoading] = useState(true)
  const scrollRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    fetchMeeting()
    const interval = setInterval(fetchMeeting, 1000)
    return () => clearInterval(interval)
  }, [id])

  useEffect(() => {
    if (scrollRef.current) {
      scrollRef.current.scrollTop = scrollRef.current.scrollHeight
    }
  }, [meeting?.transcripts?.length])

  const fetchMeeting = async () => {
    try {
      const res = await axios.get(`http://localhost:3000/api/meetings/${id}`)
      setMeeting(res.data)
      setLoading(false)
    } catch (error) {
      console.error(error)
    }
  }

  // Memoize the expensive transcript processing
  const cleanTranscripts = useMemo(() => {
    if (!meeting?.transcripts || meeting.transcripts.length === 0) return []

    const uiPattern = /(format[_\s]?size|font\s?size|font\s?color|open\s?caption[s]?|caption[s]?\s?settings|settings|arrow[_\s]?downward|jump\s?to\s?bottom|closed\s?captions|turn\s?on\s?captions|turn\s?off\s?captions|translate|language[s]?|more\s?options|default|tiny|small|medium|large|huge|jumbo|circle|white|black|blue|green|red|yellow|cyan|magenta|beta)/i
    const languagePattern = /(english|afrikaans|albanian|amharic|armenian|azerbaijani|basque|catalan|galician|georgian|icelandic|javanese|kazakh|kinyarwanda|macedonian|mongolian|northern\s?sotho|sesotho|slovenian|sundanese|swahili|swati|tshivenda|tswana|uzbek|xhosa|xitsonga|zulu|portuguese|spanish|french|german|italian|mandarin|cantonese|chinese|japanese|korean|hindi|arabic|russian|turkish|vietnamese|thai|indonesian|bengali|urdu|punjabi|tamil|telugu|marathi|gujarati|kannada|malayalam|sinhala|filipino|tagalog|malay|burmese|khmer|lao|nepali|pashto|farsi|persian|hebrew|greek|dutch|swedish|norwegian|danish|finnish|polish|czech|slovak|hungarian|romanian|bulgarian|serbian|croatian|ukrainian|lithuanian|latvian|estonian)/i
    const normalize = (s: string) => (s || '').toLowerCase().trim()

    const isGarbage = (text: string): boolean => {
      const lowerText = normalize(text)
      const noSpace = lowerText.replace(/\s+/g, '')
      if (lowerText.length < 3) return true
      if (uiPattern.test(lowerText)) return true
      if (languagePattern.test(lowerText)) return true
      if (/defaulttinysmallmediumlargehugejumbo/.test(noSpace)) return true
      if (/defaultwhiteblackbluegreenredyellowcyanmagenta/.test(noSpace)) return true
      if ((lowerText.match(/beta/g) || []).length >= 2) return true
      if (lowerText.length > 200 && /language|default|beta/.test(lowerText)) return true
      return false
    }

    const filtered = meeting.transcripts
      .filter((t: any) => {
        const text = (t.text || "").trim()
        if (!text) return false
        if (isGarbage(text)) return false
        return true
      })
      .sort((a: any, b: any) => new Date(a.timestamp).getTime() - new Date(b.timestamp).getTime())

    const seenTexts = new Set<string>()
    const finalList = filtered
      .map((t: any) => {
        const txt = String(t.text || "").trim()
        return { id: t.id, text: txt, speaker: t.speaker, timestamp: t.timestamp }
      })
      .filter((t: any) => {
        const norm = normalize(t.text)
        if (seenTexts.has(norm)) return false
        seenTexts.add(norm)
        return true
      })

    return finalList.map((t: any, idx: number) => ({
      id: t.id ?? idx,
      text: t.text,
      speaker: t.speaker,
      timestamp: t.timestamp,
      number: idx + 1,
    }))
  }, [meeting?.transcripts])

  // Auto summaries are generated by the backend every 6 minutes.
  // The UI polls meeting details and will reflect the latest summary automatically.

  if (loading)
    return (
      <div className="flex items-center justify-center h-full">
        <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-indigo-600"></div>
      </div>
    )

  if (!meeting)
    return (
      <div className="flex flex-col items-center justify-center h-full text-slate-500">
        <AlertCircle className="w-12 h-12 mb-4" />
        <h2 className="text-xl font-semibold">Meeting not found</h2>
      </div>
    )

  return (
    <div className="flex h-[calc(100vh-140px)] gap-6">
      {/* Sidebar / Info */}
      <div className="w-1/3 flex flex-col space-y-6">
        {/* Meeting Info Card */}
        <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-200">
          <h2 className="text-lg font-bold text-slate-800 mb-4">Meeting Details</h2>
          <div className="space-y-3">
            <div>
              <label className="text-xs font-semibold text-slate-400 uppercase tracking-wider">Meet URL</label>
              <p className="text-slate-700 break-all font-mono text-sm bg-slate-50 p-2 rounded mt-1">
                {meeting.meet_url}
              </p>
            </div>
            <div>
              <label className="text-xs font-semibold text-slate-400 uppercase tracking-wider">Started At</label>
              <p className="text-slate-700 mt-1">{new Date(meeting.started_at).toLocaleString()}</p>
            </div>
          </div>
        </div>

        {/* Summary Card */}
        <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-200 flex-1 flex flex-col">
          <div className="flex items-center justify-between mb-4">
            <h3 className="font-bold text-slate-800 flex items-center gap-2">
              <FileText className="w-5 h-5 text-indigo-600" /> Summary
            </h3>
            <span className="text-xs text-slate-500">Auto-updates every 6 minutes</span>
          </div>

          <div className="flex-1 overflow-y-auto pr-2 custom-scrollbar">
            {meeting.summaries?.length > 0 ? (
              <div className="prose prose-sm prose-slate max-w-none">
                {(() => {
                  const latest = [...(meeting.summaries || [])].sort(
                    (a: any, b: any) =>
                      new Date(b.created_at).getTime() - new Date(a.created_at).getTime()
                  )[0]
                  return (
                    <>
                      <div className="whitespace-pre-wrap text-slate-600 leading-relaxed">
                        {latest?.content}
                      </div>
                      <div className="mt-3 text-xs text-slate-400">
                        Last updated {latest?.created_at ? new Date(latest.created_at).toLocaleString() : ""}
                      </div>
                    </>
                  )
                })()}
              </div>
            ) : (
              <div className="h-full flex flex-col items-center justify-center text-slate-400 text-center p-4">
                <FileText className="w-10 h-10 mb-2 opacity-20" />
                <p className="text-sm">No summary generated yet.</p>
                <p className="text-xs mt-1">Summaries update automatically every 6 minutes when transcripts are present.</p>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Transcript Panel */}
      <div className="w-2/3 bg-white rounded-xl shadow-sm border border-slate-200 flex flex-col overflow-hidden">
        <div className="px-6 py-4 border-b border-slate-200 bg-slate-50">
          <h3 className="text-sm font-semibold text-slate-700">Live Transcripts ({cleanTranscripts.length})</h3>
        </div>

        <div ref={scrollRef} className="flex-1 overflow-y-auto p-6 space-y-4">
          {cleanTranscripts.length > 0 ? (
            cleanTranscripts.map((transcript: any) => (
              <div key={transcript.id} className="bg-slate-50 rounded-lg p-4 border border-slate-200">
                <div className="text-xs font-semibold text-indigo-600 mb-2">Transcript {transcript.number}</div>
                <div className="text-slate-800 leading-relaxed">{transcript.text}</div>
              </div>
            ))
          ) : (
            <div className="h-full flex flex-col items-center justify-center text-slate-400 text-center">
              <p className="text-sm">Waiting for live transcripts...</p>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

export default LiveMeeting
